apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-front
    newTag: b67a78cd9e2c3fe674c439451ac7b21e1d310011
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-back
    newTag: b67a78cd9e2c3fe674c439451ac7b21e1d310011
resources:
  - manifests.yaml