apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-front
    newTag: d390ae3bfbbc7df39778cc1d36af916c8b7b183c
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-back
    newTag: d390ae3bfbbc7df39778cc1d36af916c8b7b183c
resources:
  - manifests.yaml