apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-front
    newTag: b30774a7d3d080b4d7615570e59e58a1969de997
  - name: lucaliacr-microsoft.azurecr.io/azvote/azure-vote-back
    newTag: b30774a7d3d080b4d7615570e59e58a1969de997
resources:
  - manifests.yaml